// <auto-generated />
using System;
using FlightBooking.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBooking.Server.Migrations
{
    [DbContext(typeof(FlightBookingDbContext))]
    partial class FlightBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBooking.Server.ShoppingCart", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CurrentState");

                    b.Property<Guid?>("ExpirationId");

                    b.Property<Guid?>("OrderId");

                    b.Property<DateTime>("Updated");

                    b.Property<string>("UserName");

                    b.HasKey("CorrelationId");

                    b.ToTable("ShoppingCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
